### ISSUE TITLE
Parameter and initial set definitions in SIL

### ISSUE THREAD

**Issue by albertocasagrande** [dreossi/sapo#6]
### Description of the problem

The initial set is defined by using the `direction <n_1, n_2, ..., n_m> in [a,b]` directive in SIL. This is quite verbose and error-prone because it forces the user to both remember the ordering of the variable declarations and, for each variable, report a moltiplicator. For instance, if the model has 10 variables and the seventh one in the declaration ordering belong to the interval `[a,b]`, the user must write `direction <0,0,0,0,0,0,1,0,0,0> in [a,b]`.

Analogously, the parameter set can be defined by using either the `parameter_direction <n_1, n_2, ..., n_m> in [a,b]` directive.

### Possible improvement

I suggest to remove both the `direction` and `parameter_direction` directives and replace them with linear constrains for variables and parameters, respectively. For instance, if the variables are `v_0`,...,`v_9`, we will write `0.2*v_3 - 0.3 v_6 in [a, b]` in place of `direction <0,0,0,0.2,0,0,-0.3,0,0,0> in [a,b]`.

Analogously, if the parameters are `alpha`, `beta`,`gamma`, and `delta`, we will write `2*alpha-0.5*gamma in [a,b]` in place of `parameter_direction<2, 0, 0.5, 0> in [a,b]`. 

The new notation can also be extended by admitting equality in place of set inclusion as, for instance, in  `0.2*v_3 - 0.3 v_6 = a`.

**Comment by LucaDorigo** [comment]
I absolutely agree. This was an early choice in SIL, when I didn't fully understand the meaning of L and T matrix.
I'm already doing something similar to what you are suggesting for the definition of assertions, we can extend that also for directions.

**Comment by albertocasagrande** [comment]
Great. @LucaDorigo, can we assign this improvement to you?

**Comment by LucaDorigo** [comment]
Ok sure
